import styled from "styled-components";

/* generated by https://loading.io/ */

export default function Loading() {
  return (
    <Container>
      <LoadingWrapper>
        <div />
        <div />
        <div />
        <div />
        <div />
        <div />
        <div />
        <div />
        <div />
        <div />
        <div />
        <div />
      </LoadingWrapper>
    </Container>
  );
}

const Container = styled.div`
  width: 167px;
  height: 167px;
  display: inline-block;
  margin: auto;
`;

const LoadingWrapper = styled.div`
  width: 100%;
  height: 100%;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0;

  @keyframes loading {
    0% {
      opacity: 1;
    }
    100% {
      opacity: 0;
    }
  }

  div {
    left: 80.16px;
    top: 39.245px;
    position: absolute;
    animation: loading linear 1.5873015873015872s infinite;
    background: ${({ theme }) => theme.colors.primaryLight};
    width: 6.68px;
    height: 21.71px;
    border-radius: 3.34px / 3.9077999999999995px;
    transform-origin: 3.34px 44.254999999999995px;
  }

  div:nth-child(1) {
    transform: rotate(0deg);
    animation-delay: -1.455026455026455s;
    background: ${({ theme }) => theme.colors.primaryLight};
  }

  div:nth-child(2) {
    transform: rotate(30deg);
    animation-delay: -1.3227513227513226s;
    background: ${({ theme }) => theme.colors.primaryLight};
  }

  div:nth-child(3) {
    transform: rotate(60deg);
    animation-delay: -1.1904761904761905s;
    background: ${({ theme }) => theme.colors.primaryLight};
  }

  div:nth-child(4) {
    transform: rotate(90deg);
    animation-delay: -1.0582010582010581s;
    background: ${({ theme }) => theme.colors.primaryLight};
  }

  div:nth-child(5) {
    transform: rotate(120deg);
    animation-delay: -0.9259259259259258s;
    background: ${({ theme }) => theme.colors.primaryLight};
  }

  div:nth-child(6) {
    transform: rotate(150deg);
    animation-delay: -0.7936507936507936s;
    background: ${({ theme }) => theme.colors.primaryLight};
  }

  div:nth-child(7) {
    transform: rotate(180deg);
    animation-delay: -0.6613756613756613s;
    background: ${({ theme }) => theme.colors.primaryLight};
  }

  div:nth-child(8) {
    transform: rotate(210deg);
    animation-delay: -0.5291005291005291s;
    background: ${({ theme }) => theme.colors.primaryLight};
  }

  div:nth-child(9) {
    transform: rotate(240deg);
    animation-delay: -0.3968253968253968s;
    background: ${({ theme }) => theme.colors.primaryLight};
  }

  div:nth-child(10) {
    transform: rotate(270deg);
    animation-delay: -0.26455026455026454s;
    background: ${({ theme }) => theme.colors.primaryLight};
  }

  div:nth-child(11) {
    transform: rotate(300deg);
    animation-delay: -0.13227513227513227s;
    background: ${({ theme }) => theme.colors.primaryLight};
  }

  div:nth-child(12) {
    transform: rotate(330deg);
    animation-delay: 0s;
    background: ${({ theme }) => theme.colors.primaryLight};
  }

  div {
    box-sizing: content-box;
  }
`;
