name: make recent post list
on: push
jobs:
  make:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}

      - name: install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: set birthtime
        run: chmod +x ./.github/set-birthtime.sh && ./.github/set-birthtime.sh

      - name: make post list
        id: posts
        run: node .github/make-post-list.js

      - run: |-
          curl -L \
            -X POST \
            -H 'Accept: application/vnd.github+json' \
            -H "Authorization: Bearer ${{ secrets.DISPATCH_TARGET_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ooooorobo/dispatch-test/dispatches \
            -d '{"event_type": "test_result", "client_payload": {"posts": "${{ steps.posts.outputs.posts }}" }}'
